[lightning]
file="tidb-lightning.log"
level="debug"
[tidb]
pd-addr="127.0.0.1:2379"
[tikv-importer]
addr="127.0.0.1:20190"
[mydumper]
no-schema=true
[mydumper.csv]
separator=','
delimiter='"'
header=true
